// audio_pwm.v
// Drives a passive buzzer with a 2kHz square wave gated by a pattern envelope.
//
// Beeping schedule:
//   IDLE     : silent
//   ARMED, seconds > 20 : 1Hz beep  (50% duty: 500ms on, 500ms off)
//   ARMED, 10 < seconds <= 20 : 2Hz beep (250ms on, 250ms off)
//   ARMED, seconds <= 10 : 4Hz beep (125ms on, 125ms off)
//   DEFUSING : rapid 8Hz beep to indicate defuse in progress
//   EXPLODED : continuous 2kHz tone (solid)
//   DEFUSED  : three short chirps then silence (victory pattern)
//
// The 2kHz square wave is generated by a divide-by-(CLK_HZ/4000) counter.
// The envelope gate turns the wave on or off based on the pattern timers.
// This version uses synthesis-safe comparators instead of modulo operators
// to ensure successful routing on Gowin FPGAs.
//
// State encoding must match game_fsm.v:
//   ST_IDLE=0, ST_ARMED=1, ST_DEFUSING=2, ST_EXPLODED=3, ST_DEFUSED=4

module audio_pwm #(
    parameter integer CLK_HZ = 27_000_000
) (
    input  wire       clk,
    input  wire       reset,
    input  wire [2:0] game_state,   // from game_fsm current_state
    input  wire [3:0] seconds_tens, // from universal_counter digit3
    input  wire [3:0] seconds_ones, // from universal_counter digit2

    output reg        buzzer        // direct buzzer output pin
);

    // ----------------------------------------------------------------
    // State constants (mirror game_fsm.v)
    // ----------------------------------------------------------------
    localparam [2:0]
        ST_IDLE     = 3'd0,
        ST_ARMED    = 3'd1,
        ST_DEFUSING = 3'd2,
        ST_EXPLODED = 3'd3,
        ST_DEFUSED  = 3'd4;

    // ----------------------------------------------------------------
    // 2kHz carrier generator
    // Half-period = CLK_HZ / (2 * 2000) = CLK_HZ / 4000
    // ----------------------------------------------------------------
    localparam integer CARRIER_HALF = CLK_HZ / 4000; // ~6750 at 27MHz
    localparam integer CARRIER_BITS = $clog2(CARRIER_HALF + 1);

    reg [CARRIER_BITS-1:0] carrier_ctr;
    reg                    carrier_wave;             // toggles at 2kHz

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            carrier_ctr  <= 0;
            carrier_wave <= 1'b0;
        end else begin
            if (carrier_ctr >= CARRIER_HALF - 1) begin
                carrier_ctr  <= 0;
                carrier_wave <= ~carrier_wave;
            end else begin
                carrier_ctr <= carrier_ctr + 1;
            end
        end
    end

    // ----------------------------------------------------------------
    // 1Hz envelope tick generator (counts up to CLK_HZ cycles = 1s)
    // We derive 1Hz, 2Hz, 4Hz, 8Hz from this by comparing against thresholds.
    // ----------------------------------------------------------------
    localparam integer ONE_SEC   = CLK_HZ;           // 27M cycles = 1s
    localparam integer ENV_BITS  = $clog2(ONE_SEC + 1); // 25 bits

    reg [ENV_BITS-1:0] env_ctr;

    always @(posedge clk or posedge reset) begin
        if (reset)
            env_ctr <= 0;
        else if (env_ctr >= ONE_SEC - 1)
            env_ctr <= 0;
        else
            env_ctr <= env_ctr + 1;
    end

    // ----------------------------------------------------------------
    // Seconds value reconstruction for threshold comparisons
    // ----------------------------------------------------------------
    wire [6:0] seconds_val = seconds_tens * 7'd10 + seconds_ones;

    // ----------------------------------------------------------------
    // Synthesis-Safe Envelope Gates (No Modulo Operators)
    // We use direct mathematical boundary checks instead of % to prevent
    // massive division circuits from being synthesized on the FPGA.
    // ----------------------------------------------------------------

    // 1Hz: ON for the first half of ONE_SEC
    wire gate_1hz = (env_ctr < ONE_SEC / 2);

    // 2Hz: ON for the first quarter and third quarter
    wire gate_2hz = (env_ctr < ONE_SEC / 4) || 
                    (env_ctr >= ONE_SEC / 2 && env_ctr < 3 * ONE_SEC / 4);

    // 4Hz: ON for the first, third, fifth, and seventh eighths
    wire gate_4hz = (env_ctr < ONE_SEC / 8) || 
                    (env_ctr >= 2*ONE_SEC/8 && env_ctr < 3*ONE_SEC/8) ||
                    (env_ctr >= 4*ONE_SEC/8 && env_ctr < 5*ONE_SEC/8) || 
                    (env_ctr >= 6*ONE_SEC/8 && env_ctr < 7*ONE_SEC/8);

    // 8Hz rapid beep: Use a fast bit slice from the counter for defuse panic mode
    wire gate_8hz = (env_ctr[22] == 1'b0);

    // Defused chirp sequencer
    // Three 100ms chirps separated by 100ms gaps, then silence.
    wire defuse_chirp = (env_ctr < ONE_SEC/10) || 
                        (env_ctr >= 2*ONE_SEC/10 && env_ctr < 3*ONE_SEC/10) || 
                        (env_ctr >= 4*ONE_SEC/10 && env_ctr < 5*ONE_SEC/10);

    // ----------------------------------------------------------------
    // Envelope gate selection based on game state and seconds remaining
    // ----------------------------------------------------------------
    reg gate_clean; // 1 = buzzer on (carrier passes through), 0 = silent

    always @(*) begin
        gate_clean = 1'b0;
        case (game_state)
            ST_IDLE:     gate_clean = 1'b0;
            ST_ARMED: begin
                if (seconds_val > 7'd20)
                    gate_clean = gate_1hz;
                else if (seconds_val > 7'd10)
                    gate_clean = gate_2hz;
                else
                    gate_clean = gate_4hz;
            end
            ST_DEFUSING: gate_clean = gate_8hz;
            ST_EXPLODED: gate_clean = 1'b1; // continuous tone
            ST_DEFUSED:  gate_clean = defuse_chirp;
            default:     gate_clean = 1'b0;
        endcase
    end

    // ----------------------------------------------------------------
    // Output: carrier AND gate.
    // Registered to avoid glitch spikes from combinatorial logic.
    // ----------------------------------------------------------------
    always @(posedge clk or posedge reset) begin
        if (reset)
            buzzer <= 1'b0;
        else
            buzzer <= carrier_wave & gate_clean;
    end

endmodule